### ISSUE TITLE
Only Responds when Window is Open

### ISSUE THREAD

**Issue by aldahl** [ris58h/Touch-Tab#16]
It worked as expected up to 1.1, but beginning with 1.2, it only works for me when I have the "About Touch-Tab" window open and focused. Once the window loses focus swiping does nothing. I've verified that Accessibility is enabled and that 3-finger swipe is disabled. Rolling back to 1.1 resolves this (until the computer is put to sleep, but that's probably unrelated).

I'm seeing this on an M1 MacBook Air running Ventura 13.3.1.

**Comment by ris58h** [comment]
I've updated MacOS to 13.3.1 and I can't reproduce the issue with Touch-Tab 1.3.0 installed.
Have you tried the latest version of Touch-Tab (1.3.0)?

**Comment by aldahl** [comment]
Yes, I’m seeing the same issue with 1.2 and 1.3.

Could it be due to conflicts with other trackpad utilities? I’m running AltTab and I previously had BetterTouchTool installed, but I still see the issue even with both of those respectively closed and removed.

**Comment by ris58h** [comment]
It seems like a permission issue. Have you granted Accessibility permission to Touch-Tab? Try to revoke it and grant it again.

UPD:
1. Revoke Accessibility permission.
2. Reinstall Touch-Tab.
3. Grant Accessibility permission.

**Comment by aldahl** [comment]
Accessibility permission has been granted, and I do not see the warning indicator on the menu bar icon.

I followed the steps with no luck. I'm fairly new to MacOS and am not very familiar with how permissions work. In Activity Monitor the process is running under my user. Is there anything else I can do to verify that it's running correctly?

**Comment by aldahl** [comment]
For good measure, I ran `sudo tccutil reset Accessibility`, restarted, and reenabled Accessibility permission, but I'm still having the issue.

**Comment by ris58h** [comment]
Do you have several copies of Touch-Tab installed? You can check it by searching Touch-Tab in Spotlight.

Currently I'm working on [sandboxed](https://github.com/ris58h/Touch-Tab/files/11324073/Touch-Tab.Pro.app.zip) version of Touch-Tab that could be published in App Store. Could you try it?

**Comment by aldahl** [comment]
I only see one copy installed. The sandboxed version works great though! I look forward to seeing it in the App Store!

The only issue I’m seeing now is that it is unresponsive after the computer wakes from sleep (even with the “About” window open) and I have to relaunch it before it works. I was seeing this in 1.1 as well.

**Comment by ris58h** [comment]
> The sandboxed version works great though!

Good to hear.

> The only issue I’m seeing now is that it is unresponsive after the computer wakes from sleep

I run into the same issue sometimes but I can't reproduce it. Do you get it every time after sleep?

**Comment by aldahl** [comment]
I got it every time with 1.0-1.3, but I've only seen it once with the sandboxed version. I'll try to pay attention to see if there's any pattern that causes it. Does MacOS produce any logs that could be helpful?

**Comment by ris58h** [comment]
> MacOS produce any logs that could be helpful?

Not that I'm aware of. Anyway thank your for your help.

**Comment by aldahl** [comment]
Thank you for making such a great utility!

I'll leave it up to you if you want this issue closed, as the problem described has been resolved for me. Thank you again!

**Comment by ris58h** [comment]
Should be fixed in [1.4.0](https://github.com/ris58h/Touch-Tab/releases/tag/v1.4.0)

@aldahl Could you check it?

**Comment by aldahl** [comment]
I apologize for the delay.

I removed the previously installed version, installed 1.4, and reauthorized Accessibility, but I'm still having the same issue with it. The pro version linked above does still work though. I have also updated to the MacOS 14.0 beta and am seeing the same thing with it.

**Comment by ris58h** [comment]
@aldahl thank you for checking it. I believe that I figured out what's going on. Could you check another version? 
[Touch-Tab-issue16.app.zip](https://github.com/ris58h/Touch-Tab/files/12643055/Touch-Tab-issue16.app.zip)

**Comment by aldahl** [comment]
@ris58h Thanks, that version works!

**Comment by ris58h** [comment]
@aldahl the fix is available in [1.4.1](https://github.com/ris58h/Touch-Tab/releases/tag/v1.4.1)
